#server:
#  port: 8181
#  servlet:
#    context-path: /
spring:
  application:
    name: shop-client
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config_server
  thymeleaf:
    encoding: UTF-8
    prefix: file:Shop/src/main/resources/templates/
    cache: false
  jackson:
    serialization:
      indent_output: true
  web:
    resources:
      static-locations: file:Shop/src/main/resources/static/
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./data/market;MODE=PostgreSQL;AUTO_SERVER=TRUE
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        default_schema: 'public'
        temp:
          use_jdbc_metadata_defaults: false
  flyway:
    baseline-on-migrate: true