#server:
#  port: 8181
#  servlet:
#    context-path: /
spring:
  application:
    name: shop-client
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config_server
  thymeleaf:
    encoding: UTF-8
    prefix: file:Shop/src/main/resources/templates/
    cache: false
  jackson:
    serialization:
      indent_output: true
  web:
    resources:
      static-locations: file:Shop/src/main/resources/static/
