create table baskets (
    id int8 generated by default as identity,
    user_id int8,
    primary key (id)
);

alter table if exists buckets
    add constraint basket_fk_user
    foreign key (user_id) references users;

create table basket_products (
    basket_id int8 not null,
    product_id bigint not null
);

alter table if exists basket_products
    add constraint basket_products_fk_product
    foreign key (product_id) references products;

alter table if exists basket_products
    add constraint basket_products_fk_bucket
    foreign key (basket_id) references baskets;