eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    news-service:
      path: /news/**
      serviceId: news-client
    users:
      path: /**
      url: http://localhost:8081/
