server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./data/market;MODE=PostgreSQL;AUTO_SERVER=TRUE
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        default_schema: 'public'
        temp:
          use_jdbc_metadata_defaults: fals
  flyway:
    baseline-on-migrate: true