server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config
  #        git:
  #          uri:
  #          search-paths:
  #          clone-on-start:
  application:
    name: config_server

logging:
  level:
    org.springframework.cloud: TRACE