-- CATEGORIES
create table categories (
    id bigint generated by default as identity,
    title varchar(255),
    primary key (id)
);

-- PRODUCTS
create table products (
    id bigint generated by default as identity,
    price integer,
    title varchar(255),
    primary key (id)
);

-- PRODUCTS AND CATEGORIES
create table products_categories (
    product_id bigint not null,
    category_id bigint not null
);

alter table products_categories
    add constraint products_categories_fk_categories
        foreign key (category_id) references categories;

alter table products_categories
    add constraint products_categories_fk_products
        foreign key (product_id) references products;

-- ROLES
create table roles (
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);

-- USERS
create table users (
    id bigint generated by default as identity,
    email varchar(255),
    locked boolean,
    password varchar(255),
    username varchar(255),
    primary key (id)
);

-- USER AND ROLES
create table users_roles (
    user_id bigint not null,
    role_id bigint not null
);

alter table users_roles
    add constraint users_roles_fk_roles
    foreign key (role_id) references roles;

alter table users_roles
    add constraint users_roles_fk_users
    foreign key (user_id) references users;